source "https://rubygems.org"

# NOTE: Need edge Rails to run minitest v6 (https://github.com/rails/rails/pull/56202)
# gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 8.1.1"
# The modern asset pipeline for Rails [https://github.com/rails/propshaft]
gem "propshaft"
# Use sqlite3 as the database for Active Record
gem "sqlite3", ">= 2.1"
# Use the Puma web server [https://github.com/puma/puma]
gem "puma", ">= 5.0"
# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
gem "importmap-rails"
# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem "turbo-rails"
# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem "stimulus-rails"
# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ windows jruby ]

# Use the database-backed adapters for Rails.cache, Active Job, and Action Cable
gem "solid_cache"
gem "solid_queue"
gem "solid_cable"

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Deploy this application anywhere as a Docker container [https://kamal-deploy.org]
gem "kamal", require: false

# Add HTTP asset caching/compression and X-Sendfile acceleration to Puma [https://github.com/basecamp/thruster/]
gem "thruster", require: false

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
gem "image_processing", "~> 1.2"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"

  # Audits gems for known security defects (use config/bundler-audit.yml to ignore issues)
  gem "bundler-audit", require: false

  # Static analysis for security vulnerabilities [https://brakemanscanner.org/]
  gem "brakeman", require: false

  # Omakase Ruby styling [https://github.com/rails/rubocop-rails-omakase/]
  gem "rubocop-rails-omakase", require: false
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console"
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem "capybara"
  gem "selenium-webdriver"
end
gem 'async'
gem 'async-io'
# use a legacy version which supports Ruby 3.0
# we use this repo with Ruby 3.0 for testing the knapsack_pro gem
gem 'fiber-local', '1.0.0'

group :development, :test do
  gem 'spring'
  gem 'spring-commands-cucumber'
  gem 'spring-commands-rspec'

  if ENV['USE_KNAPSACK_PRO_FROM_RUBYGEMS']
    gem 'knapsack_pro'
  else
    gem 'knapsack_pro', path: "../"
  end

  unless ENV["MINITEST"]
    gem 'test-unit-rails'
  end

  gem 'listen'
end

group :test do
  gem 'rails-controller-testing'

  if ENV['KNAPSACK_PRO_RSPEC_DISABLED'] != 'true'
    gem 'rspec-rails'
    gem 'rspec_junit_formatter'
    gem 'rspec-retry'
    # gem 'rspec-core'
    gem 'async-rspec', require: false
  end

  gem 'cucumber-rails', require: false
  gem 'database_cleaner'
  gem 'spinach'
  gem 'timecop'
  gem 'vcr' # Needed to test https://github.com/KnapsackPro/knapsack_pro-ruby/pull/251
  gem 'webmock', require: false # Needed to test https://github.com/KnapsackPro/knapsack_pro-ruby/pull/251
  gem 'capybara-screenshot'
  gem 'shared_should', require: false
  gem 'simplecov', require: false
end

gem 'turnip', '~> 4.4'
gem 'juniter'
gem 'minitest', '~> 5.27'
